/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package material.design;

/**
 *
 * @author client
 */
public class pan_time extends javax.swing.JPanel {

    /**
     * Creates new form pan_time
     */
    public pan_time() {
        initComponents();
    }
    
    
    public String getbignTime(){
        return textField1.getText();
    }
    public String getfinTime(){
        return textField2.getText();
    }
    
     public void setbignTime(String str){
        textField1.setText( str);
    }
    public void setfinTime(String str){
        textField2.setText(str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timePicker1 = new timePcker.TimePicker();
        timePicker2 = new timePcker.TimePicker();
        textField1 = new material.design.TextField();
        textField2 = new material.design.TextField();

        timePicker1.setDisplayText(textField1);

        timePicker2.setDisplayText(textField2);

        setBackground(new java.awt.Color(255, 255, 255));

        textField1.setForeground(new java.awt.Color(204, 0, 51));
        textField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        textField1.setLabelText("من");
        textField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textField1MouseClicked(evt);
            }
        });
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        textField2.setForeground(new java.awt.Color(204, 0, 51));
        textField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        textField2.setLabelText("إلى");
        textField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textField2MouseClicked(evt);
            }
        });
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textField1MouseClicked
        timePicker1.showPopup(this, (getWidth() - timePicker1.getPreferredSize().width) / 2, (getHeight() - timePicker1.getPreferredSize().height) / 2);
    }//GEN-LAST:event_textField1MouseClicked

    private void textField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textField2MouseClicked
        timePicker2.showPopup(this, (getWidth() - timePicker2.getPreferredSize().width) / 2, (getHeight() - timePicker2.getPreferredSize().height) / 2);
    }//GEN-LAST:event_textField2MouseClicked

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.TextField textField1;
    private material.design.TextField textField2;
    private timePcker.TimePicker timePicker1;
    private timePcker.TimePicker timePicker2;
    // End of variables declaration//GEN-END:variables
}
