/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package guis;

import DialogFram.ValidationMessageDialog;
import domaine.CategoreNiveau;
import domaine.Enseignant;
import domaine.Matiere;
import domaine.EnseignantMatiere;
import domaine.NiveauEtude;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import main.java.com.school.impl.CategoreNiveauDAOImpl;
import main.java.com.school.impl.EnseignantDAOImpl;
import main.java.com.school.impl.EnseignantMatiereDAOImpl;
import main.java.com.school.impl.MatiereDAOImpl;
import main.java.com.school.impl.NiveauEtudeDAOImpl;
import main.java.com.school.model.config.ConnectionDB;
import main.java.com.school.model.config.DatabaseConnectionException;
import material.design.ScrollBar;
import ui.table.TableCustom;

/**
 *
 * @author client
 */
public class AddMatiereForm1 extends javax.swing.JDialog {

    Home home;
    Connection connection;
    CategoreNiveauDAOImpl categoreNiveauDAOImpl;
    NiveauEtudeDAOImpl niveauEtudeDAOImpl;
    ValidationMessageDialog message_validation;
    MatiereDAOImpl matiereDAOImpl;
    EnseignantDAOImpl enseignantDAOImpl;
    EnseignantMatiereDAOImpl enseignant_matiere_dao;

    public AddMatiereForm1(java.awt.Frame parent, boolean modal) {
        super(parent);
        this.home = (Home) parent;
        message_validation = new ValidationMessageDialog(this.home);
        try {
            connection = ConnectionDB.getConnection();
        } catch (DatabaseConnectionException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        categoreNiveauDAOImpl = new CategoreNiveauDAOImpl(connection);
        niveauEtudeDAOImpl = new NiveauEtudeDAOImpl(connection);
        matiereDAOImpl = new MatiereDAOImpl(connection);
        enseignantDAOImpl = new EnseignantDAOImpl(connection);
        enseignant_matiere_dao = new EnseignantMatiereDAOImpl(connection);

        initComponents();
        setLocationRelativeTo(this);
        prapareUI();
        com_ensig.setSelectedIndex(0);

    }

    public void prapareUI() {
        setInfoCategoreNiveauInCombox();
        setInfoEnsignInCom();

    }

    public void setInfoCategoreNiveauInCombox() {
        List<CategoreNiveau> categoreNiveaus = categoreNiveauDAOImpl.findAll();
        for (CategoreNiveau categoreNiveau_obj : categoreNiveaus) {
            com_catego_niveau.addItem(categoreNiveau_obj.getCategore_niveau_ar());
            //    jComboBox1.addItem(categoreNiveau_obj.getCategore_niveau_ar());
        }
    }

    public void setInfoNiveauEtudeInCom() {
        CategoreNiveau category = categoreNiveauDAOImpl.findByName(com_catego_niveau.getSelectedItem().toString(), "categore_niveau_ar");
        List<NiveauEtude> niveauEtudes = niveauEtudeDAOImpl.findAll();
        
        com_niveau.removeAllItems();
        if (com_catego_niveau.getSelectedIndex() != -1) {
            for (NiveauEtude obj : niveauEtudes) {
                if (obj.getCategore_niveau_id() == category.getId()) {
                    com_niveau.addItem(obj.getNiveauInitialAr());
                }
            }
        }
    }

    public void setInfoEnsignInCom() {
        List<Enseignant> enseignants = enseignantDAOImpl.findAll();
        com_ensig.removeAll();

        for (Enseignant enseignant : enseignants) {
            com_ensig.addItem(enseignant.getNomAr() + "-" + enseignant.getPrenomAr());
        }
        com_ensig.addItem("/");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_matier = new material.design.TextField();
        txt_matier_fr = new material.design.TextField();
        com_niveau = new material.design.Combobox();
        com_catego_niveau = new material.design.Combobox();
        buttonRounder17 = new material.design.buttonRounder();
        buttonRounder19 = new material.design.buttonRounder();
        jLabel2 = new javax.swing.JLabel();
        txt_prix = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        com_ensig = new material.design.Combobox();
        lab_categ_niv = new javax.swing.JLabel();
        lab_niv_ = new javax.swing.JLabel();
        lab_ensig = new javax.swing.JLabel();
        lab_ma = new javax.swing.JLabel();
        nbrSceanceParSomaine = new material.design.TextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_matier.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_matier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_matier.setLabelText("المــادة");
        txt_matier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_matierKeyTyped(evt);
            }
        });
        jPanel1.add(txt_matier, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 237, 158, -1));

        txt_matier_fr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_matier_fr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_matier_fr.setLabelText("La Matiere");
        txt_matier_fr.setLangue(1);
        jPanel1.add(txt_matier_fr, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 237, 145, -1));

        com_niveau.setLabeText("القـسـم");
        com_niveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_niveauActionPerformed(evt);
            }
        });
        jPanel1.add(com_niveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 53, 190, 60));

        com_catego_niveau.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        com_catego_niveau.setLabeText("المستوى الدراسي");
        com_catego_niveau.setPreferredSize(new java.awt.Dimension(64, 46));
        com_catego_niveau.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                com_catego_niveauItemStateChanged(evt);
            }
        });
        com_catego_niveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_catego_niveauActionPerformed(evt);
            }
        });
        jPanel1.add(com_catego_niveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 53, 200, 60));

        buttonRounder17.setBackground(new java.awt.Color(255, 51, 51));
        buttonRounder17.setForeground(new java.awt.Color(255, 255, 255));
        buttonRounder17.setText("إلغاء");
        jPanel1.add(buttonRounder17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 120, 40));

        buttonRounder19.setBackground(new java.awt.Color(51, 153, 0));
        buttonRounder19.setForeground(new java.awt.Color(255, 255, 255));
        buttonRounder19.setText("حفظ");
        buttonRounder19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRounder19ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRounder19, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 330, 140, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(150, 150, 150));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("المبلغ");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 231, -1, 60));

        txt_prix.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_prix.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_prix.setText("00.00");
        txt_prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prixActionPerformed(evt);
            }
        });
        txt_prix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prixKeyTyped(evt);
            }
        });
        jPanel1.add(txt_prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 231, 142, 60));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("اضافة المواد الدراسية");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 0, 566, 33));

        com_ensig.setLabeText("أستاذ المادة");
        com_ensig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_ensigActionPerformed(evt);
            }
        });
        jPanel1.add(com_ensig, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 157, 153, -1));

        lab_categ_niv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_categ_niv.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lab_categ_niv, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 124, 207, 20));

        lab_niv_.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_niv_.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lab_niv_, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 124, 207, 20));

        lab_ensig.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_ensig.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lab_ensig, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 216, 207, 20));

        lab_ma.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_ma.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lab_ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 296, 281, 20));

        nbrSceanceParSomaine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nbrSceanceParSomaine.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nbrSceanceParSomaine.setLabelText("عدد الحصص في الاسبوع");
        nbrSceanceParSomaine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nbrSceanceParSomaineKeyTyped(evt);
            }
        });
        jPanel1.add(nbrSceanceParSomaine, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 157, 130, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("دج");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 30, 40));

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void com_catego_niveauItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_com_catego_niveauItemStateChanged
        if (com_catego_niveau.getSelectedIndex() != -1) {
            com_niveau.removeAllItems();
            // setInfoNiveauEtudeInCom(com_catego_niveau.getSelectedIndex()+1);
        }
    }//GEN-LAST:event_com_catego_niveauItemStateChanged

    private void com_catego_niveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_catego_niveauActionPerformed
        setInfoNiveauEtudeInCom();
        lab_categ_niv.setText("");
    }//GEN-LAST:event_com_catego_niveauActionPerformed

    private void buttonRounder19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRounder19ActionPerformed
            
        try {
            
            CategoreNiveau categoreNiveau = categoreNiveauDAOImpl.getCategory_by_name(com_catego_niveau.getSelectedItem().toString());
            NiveauEtude niveauEtude = niveauEtudeDAOImpl.getNiveauOfCategory(com_niveau.getSelectedItem().toString(), com_catego_niveau.getSelectedItem().toString());
            String matiere_name=txt_matier.getText();
            String niveau_etude=com_niveau.getSelectedItem().toString();
            String categorie_niveau= com_catego_niveau.getSelectedItem().toString();
            
//            Matiere matiere_obj=matiereDAOImpl.getMatiereNiveauOfCategory(txt_matier.getText(), com_niveau.getSelectedItem().toString(),
//                com_catego_niveau.getSelectedItem().toString());
            Matiere matiere_obj=matiereDAOImpl.getMatiereNiveauOfCategory(matiere_name, niveau_etude,categorie_niveau);
            
        if ( !Objects.isNull(matiere_obj)  ) { // test exist matiere not exist
            JOptionPane.showMessageDialog(null, "This Matiere deja exist in this niveau");
            return;
        }
        
        if (txt_matier.getText().equals("") | txt_matier_fr.getText().equals("") 
                | txt_prix.getText().equals("00.00")| nbrSceanceParSomaine.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "الرجاء التأكد من ادخال المعلومات");
            return;
        }
        
            Enseignant enseignant = null;
            String name = com_ensig.getSelectedItem().toString();
            String nom = name.split("-")[0];
            String prenom = name.split("-")[1];

            enseignant = enseignantDAOImpl.findByFullName(nom, prenom);

            String Txt_nbr_sceance_par_somaine = nbrSceanceParSomaine.getText();
            int SceanceParSomaine = (Txt_nbr_sceance_par_somaine.equals("")) ? 0 : (Integer.parseInt(Txt_nbr_sceance_par_somaine));

            Matiere matiere = new Matiere(0, txt_matier.getText(), txt_matier_fr.getText(),
                    0, niveauEtude, categoreNiveau, enseignant, SceanceParSomaine, SceanceParSomaine * 4);
            
            EnseignantMatiere enseignant_matiere = enseignant_matiere_dao.findByNamesEnseignantMatiere(enseignant, matiere);
                   if (!Objects.isNull(enseignant_matiere) ){
                       JOptionPane.showMessageDialog(null, "This prof is affected with same matiere");
                       return;
                   }
            if (matiereDAOImpl.save(matiere) > 0) {
                   matiere = matiereDAOImpl.getMatiereNiveauOfCategory(txt_matier.getText(), com_niveau.getSelectedItem().toString(), com_catego_niveau.getSelectedItem().toString());
                   // verivise si existe this relation id_ense,id_mat
                   
                   double prix=Double.parseDouble(txt_prix.getText());
                   int num_seance_semaine=Integer.parseInt(Txt_nbr_sceance_par_somaine);
                   
                   int num_seance_monis = num_seance_semaine * 4;
                           
                   enseignant_matiere=new EnseignantMatiere(0, enseignant, matiere, LocalDate.now(),num_seance_semaine,num_seance_monis,prix);
                   if (enseignant_matiere_dao.save(enseignant_matiere)>0) {
                    JOptionPane.showMessageDialog(null, "Save Succesful matiere and prof");
                    
                    this.dispose();
                home.setInfoMatiereInTab(home.getidCategoryOfTabCategorys(), home.getidNiveauOfTabNiveaus());
                this.message_validation.showMessage("تأكيد", "لقد تم الحفظ بنجاح");
                }
               }
        } catch (SQLException ex) {
            Logger.getLogger(AddMatiereForm1.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_buttonRounder19ActionPerformed

    private void txt_prixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prixKeyTyped
        char ch = evt.getKeyChar();
        //if(prix.getText().c)
        if ((!Character.isDigit(ch) && ch != '.') || (txt_prix.getText().contains(".") && !Character.isDigit(ch))) {
            getToolkit().beep();
            evt.consume(); // Ignore the key event
        }
    }//GEN-LAST:event_txt_prixKeyTyped

    private void com_niveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_niveauActionPerformed
        lab_niv_.setText("");
    }//GEN-LAST:event_com_niveauActionPerformed

    private void com_ensigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_ensigActionPerformed
        lab_ensig.setText("");
    }//GEN-LAST:event_com_ensigActionPerformed

    private void txt_matierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_matierKeyTyped
        lab_ma.setText("");
    }//GEN-LAST:event_txt_matierKeyTyped

    private void nbrSceanceParSomaineKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nbrSceanceParSomaineKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nbrSceanceParSomaineKeyTyped

    private void txt_prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMatiereForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMatiereForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMatiereForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMatiereForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home home = new Home();
                AddMatiereForm1 dialog = new AddMatiereForm1(home, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.buttonRounder buttonRounder17;
    private material.design.buttonRounder buttonRounder19;
    private material.design.Combobox com_catego_niveau;
    private material.design.Combobox com_ensig;
    private material.design.Combobox com_niveau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab_categ_niv;
    private javax.swing.JLabel lab_ensig;
    private javax.swing.JLabel lab_ma;
    private javax.swing.JLabel lab_niv_;
    private material.design.TextField nbrSceanceParSomaine;
    private material.design.TextField txt_matier;
    private material.design.TextField txt_matier_fr;
    private javax.swing.JTextField txt_prix;
    // End of variables declaration//GEN-END:variables

}
