/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package guis;

import DialogFram.ValidationMessageDialog;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import domaine.CategoreNiveau;
import domaine.NiveauEtude;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import main.java.com.school.impl.CategoreNiveauDAOImpl;
import main.java.com.school.impl.NiveauEtudeDAOImpl;
import main.java.com.school.model.config.ConnectionDB;
import main.java.com.school.model.config.DatabaseConnectionException;
import material.design.ScrollBar;
import ui.table.TableCustom;

public class AddNiveauForm extends javax.swing.JDialog {

    home home;
    Connection connection;
    CategoreNiveauDAOImpl categoreNiveauDAOImpl;
    NiveauEtudeDAOImpl niveauEtudeDAOImpl;
    ValidationMessageDialog message_validation;

    public AddNiveauForm(java.awt.Frame parent) {
        super(parent);
        this.home = (home) parent;
        try {
            connection = new ConnectionDB().getConnection();
        } catch (DatabaseConnectionException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        categoreNiveauDAOImpl = new CategoreNiveauDAOImpl(connection);
        niveauEtudeDAOImpl = new NiveauEtudeDAOImpl(connection);
        initComponents();
        setLocationRelativeTo(this);
        setDesignTable(tab_niveau, jScrollPane2);

        prapareUI();
    }

    public void prapareUI() {
        setInfoCategoreNiveauInCombox();
    }

    public void setInfoCategoreNiveauInCombox() {
        categoreNiveauDAOImpl = new CategoreNiveauDAOImpl(connection);
        List<CategoreNiveau> categoreNiveaus = categoreNiveauDAOImpl.findAll();
        for (CategoreNiveau categoreNiveau_obj : categoreNiveaus) {
            com_categore_niveau.addItem(categoreNiveau_obj.getCategore_niveau_ar());
            //    jComboBox1.addItem(categoreNiveau_obj.getCategore_niveau_ar());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_annul = new material.design.buttonRounder();
        btn_save = new material.design.buttonRounder();
        txt_niveau = new material.design.TextField();
        txt_niveau_fr = new material.design.TextField();
        btn_add_niveau = new material.design.buttonRounder();
        textAreaScroll1 = new material.design.TextAreaScroll();
        txt_descrp = new material.design.TextArea();
        jLabel2 = new javax.swing.JLabel();
        btn_delet = new material.design.buttonRounder();
        tableScrollButton1 = new ui.table.TableScrollButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_niveau = new javax.swing.JTable();
        com_categore_niveau = new material.design.Combobox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(101, 147, 252));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("أقسام دراسية جدية");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_annul.setBackground(new java.awt.Color(255, 51, 51));
        btn_annul.setForeground(new java.awt.Color(255, 255, 255));
        btn_annul.setText("إلغاء");

        btn_save.setBackground(new java.awt.Color(51, 153, 0));
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("حفظ");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        txt_niveau.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_niveau.setToolTipText("");
        txt_niveau.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_niveau.setLabelText("قسم جديد\n");
        txt_niveau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_niveauKeyTyped(evt);
            }
        });

        txt_niveau_fr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_niveau_fr.setToolTipText("");
        txt_niveau_fr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_niveau_fr.setLabelText("Nouveau classe");
        txt_niveau_fr.setLangue(1);
        txt_niveau_fr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_niveau_frActionPerformed(evt);
            }
        });

        btn_add_niveau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus - Copie - Copie.png"))); // NOI18N
        btn_add_niveau.setText("اضافة القسم ");
        btn_add_niveau.setToolTipText("Nouvelle Type");
        btn_add_niveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_niveauActionPerformed(evt);
            }
        });

        textAreaScroll1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        textAreaScroll1.setLabelText("Description ");

        txt_descrp.setColumns(20);
        txt_descrp.setRows(3);
        txt_descrp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textAreaScroll1.setViewportView(txt_descrp);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("الوصف  :");

        btn_delet.setForeground(new java.awt.Color(255, 255, 255));
        btn_delet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/supprimer (1).png"))); // NOI18N
        btn_delet.setToolTipText("Annnuler la command");
        btn_delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletActionPerformed(evt);
            }
        });

        tab_niveau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الوصف", "classe", "القسم"
            }
        ));
        tab_niveau.setSelectionBackground(new java.awt.Color(235, 235, 235));
        jScrollPane2.setViewportView(tab_niveau);

        tableScrollButton1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        com_categore_niveau.setLabeText("المستوى الدراسي");
        com_categore_niveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_categore_niveauActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(383, 383, 383)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(com_categore_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textAreaScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_delet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btn_add_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_niveau_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(9, 9, 9)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_annul, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(com_categore_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_niveau_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAreaScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btn_delet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_annul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
       boolean exist=false;
        int id_categoryNiveau = 0;
        DefaultTableModel model = (DefaultTableModel) tab_niveau.getModel();
        if (tab_niveau.getRowCount() != 0) {
            List<CategoreNiveau> categoreNiveaus = categoreNiveauDAOImpl.findAll();
            List<NiveauEtude> niveauEtudes = niveauEtudeDAOImpl.findAll();
            
            for (CategoreNiveau categoreNiveauobj : categoreNiveaus) {
                if (categoreNiveauobj.getCategore_niveau_ar().equals(com_categore_niveau.getSelectedItem())) {
                    id_categoryNiveau = categoreNiveauobj.getId();
                     break;
                }
            }
            
            List<String > list_niveau_exist = new ArrayList<>();
            for(NiveauEtude niveauEtude_ob :niveauEtudes){
                for (int row = 0; row < model.getRowCount(); row++) {
                   
                if(niveauEtude_ob.getNiveauInitialAr().equals(model.getValueAt(row, 2).toString()) &&
                        niveauEtude_ob.getCategore_niveau_id() == id_categoryNiveau ){
                list_niveau_exist.add(model.getValueAt(row, 2).toString());
                exist =true;
                }    
                 }
            }
            
                if(!exist){   // new
                for (int row = 0; row < model.getRowCount(); row++) {
                    JOptionPane.showMessageDialog(null, "in save model");
                    NiveauEtude niveauEtude = new NiveauEtude(0, model.getValueAt(row, 2).toString(), model.getValueAt(row, 1).toString(), model.getValueAt(row, 0).toString(), id_categoryNiveau);
                    niveauEtudeDAOImpl.save(niveauEtude);
                }
                 this.dispose();
                message_validation =new ValidationMessageDialog(AddNiveauForm.this,home);
                message_validation.showMessage(" تأكيد العملية","تمت إضافةالأقسام الدراسية بنجاج  .");               
                }
                else{   // exist
                  jLabel5.setText(list_niveau_exist.toString() + " : " + " موجودة" );
                }         
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletActionPerformed
        if (tab_niveau.getSelectedRow() != -1) {
            DefaultTableModel model = (DefaultTableModel) tab_niveau.getModel();
            model.removeRow(tab_niveau.getSelectedRow());
            jLabel5.setText("");
        }
    }//GEN-LAST:event_btn_deletActionPerformed

    private void btn_add_niveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_niveauActionPerformed
        if (com_categore_niveau.getSelectedIndex() != -1) {
            if (!txt_niveau.getText().isEmpty()) {
                String niveau = txt_niveau.getText();
                String niveau_fr = txt_niveau_fr.getText();
                String descrip = txt_descrp.getText();
                DefaultTableModel model = (DefaultTableModel) tab_niveau.getModel();
                model.addRow(new Object[]{descrip, niveau_fr,niveau});
                cleanItems();
            } else {
                jLabel3.setText("ادخل اسم القسم");
            }
        } else {
            jLabel4.setText("إختر المستوى");
        }


    }//GEN-LAST:event_btn_add_niveauActionPerformed

    private void txt_niveau_frActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_niveau_frActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_niveau_frActionPerformed

    private void com_categore_niveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_categore_niveauActionPerformed
        if (com_categore_niveau.getSelectedIndex() != -1)
            jLabel4.setText("");
    }//GEN-LAST:event_com_categore_niveauActionPerformed

    private void txt_niveauKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_niveauKeyTyped
        jLabel3.setText("");
    }//GEN-LAST:event_txt_niveauKeyTyped

    public void setDesignTable(JTable tab, JScrollPane scrol) {
        TableCustom.apply(scrol, TableCustom.TableType.DEFAULT);
        tab.getTableHeader().setFont(new Font("", Font.BOLD, 15));
        tab.setFont(new Font("", Font.BOLD, 14));
        scrol.setVerticalScrollBar(new ScrollBar());
        scrol.getVerticalScrollBar().setBackground(Color.WHITE);
        scrol.getViewport().setBackground(Color.white);// make table without rouw white
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        scrol.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);

    }
    
    public void cleanItems(){
    txt_niveau.setText("");
            txt_niveau_fr.setText("");
            txt_descrp.setText("");
            jLabel3.setText("");
         
    
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNiveauForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNiveauForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNiveauForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNiveauForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNiveauForm dialog = new AddNiveauForm(new home());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.buttonRounder btn_add_niveau;
    private material.design.buttonRounder btn_annul;
    private material.design.buttonRounder btn_delet;
    private material.design.buttonRounder btn_save;
    private material.design.Combobox com_categore_niveau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tab_niveau;
    private ui.table.TableScrollButton tableScrollButton1;
    private material.design.TextAreaScroll textAreaScroll1;
    private material.design.TextArea txt_descrp;
    private material.design.TextField txt_niveau;
    private material.design.TextField txt_niveau_fr;
    // End of variables declaration//GEN-END:variables
}
