/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package guis;

import domaine.Payement;
import domaine.PayementDetaille;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import main.java.com.school.impl.PayementDetailleDAOImp;
import main.java.com.school.model.config.ConnectionDB;
import main.java.com.school.model.config.DatabaseConnectionException;

/**
 *
 * @author client
 */
public class CreditDetailleForm extends javax.swing.JDialog {

    Payement payement;
    
    public CreditDetailleForm(java.awt.Frame parent, boolean modal, Payement payement) {
        super(parent, modal);
        this.payement=payement; 
         setLocationRelativeTo(this);
        initComponents();
        
        setInfoPaymentCreditInTable(payement);
    }

    public void setInfoPaymentCreditInTable(Payement payement){
   DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
   model.setRowCount(0);
        try 
        {
            List<PayementDetaille> payementDetailles= new PayementDetailleDAOImp(ConnectionDB.getConnection()).getPayementDetailleCredit(payement.getId());
            int nb_seance=payementDetailles.size();
            int nb_seance_payee=0;
            int nb_seance_no_payee=0;
            for (PayementDetaille payementDetaille : payementDetailles) {
               if(payementDetaille.getMontant()==0) nb_seance_no_payee=nb_seance_no_payee+1;
               else nb_seance_payee=nb_seance_payee+1;
                model.addRow(new Object[]{payementDetaille.getDate_payement(),payementDetaille.getMontant(),payementDetaille.getSeance().getId(),
                    payementDetaille.getSeance().getMatiere().getMatiereEtdAr(),payementDetaille.getId(),payement.getId()});
            }
            lab_nb_seance.setText(nb_seance+"");
            lab_nb_seance_payee.setText(nb_seance_payee+"");
            lab_nb_seance_no_payee.setText(nb_seance_no_payee+"");
            
        } catch (DatabaseConnectionException ex) {
            Logger.getLogger(CreditDetailleForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tableScrollButton1 = new ui.table.TableScrollButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lab_nb_seance = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lab_nb_seance_payee = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lab_nb_seance_no_payee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("الحصص المدروسة بديون");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 152, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ملاحضة", "تاريخ الدفع", "الثمن", "رقم الحصة", "المادة", "Id_pay_detaille", "Id_payement"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        tableScrollButton1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(tableScrollButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 42, 755, 220));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("العدد الإجمالي للحصص");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 274, -1, 27));

        lab_nb_seance.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab_nb_seance.setForeground(new java.awt.Color(0, 51, 204));
        lab_nb_seance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_nb_seance.setText("0");
        jPanel1.add(lab_nb_seance, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 274, 140, 27));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("عدد الحصص المدفوع");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 313, -1, 27));

        lab_nb_seance_payee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab_nb_seance_payee.setForeground(new java.awt.Color(0, 51, 204));
        lab_nb_seance_payee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_nb_seance_payee.setText("0");
        jPanel1.add(lab_nb_seance_payee, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 313, 130, 27));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("عدد الحصص الغير مدفوعة ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 346, -1, 27));

        lab_nb_seance_no_payee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab_nb_seance_no_payee.setForeground(new java.awt.Color(0, 51, 204));
        lab_nb_seance_no_payee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_nb_seance_no_payee.setText("0");
        jPanel1.add(lab_nb_seance_no_payee, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 346, 100, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditDetailleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditDetailleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditDetailleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditDetailleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CreditDetailleForm dialog = new CreditDetailleForm(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lab_nb_seance;
    private javax.swing.JLabel lab_nb_seance_no_payee;
    private javax.swing.JLabel lab_nb_seance_payee;
    private ui.table.TableScrollButton tableScrollButton1;
    // End of variables declaration//GEN-END:variables
}
