/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import Service.MatiereService;
import Service.SeanceService;
import domaine.Matiere;
import domaine.Seance;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import main.java.com.school.model.config.DatabaseConnectionException;

/**
 *
 * @author farid
 */
public class Panel_PresenceUI extends javax.swing.JPanel {

    /**
     * Creates new form Panel_PresenceUI
     */
    MatiereService matiere_service=new MatiereService();
    SeanceService seance_service=new SeanceService();
    List <Seance> list_seance_about_all_matieres=new ArrayList<>();
    public Panel_PresenceUI() {
        initComponents();
    }
    
    public void prepareUI() throws SQLException{
    
        try {
            checkSeancesAndSaveNewSeance();
            setSeanceInTable();
            this.list_seance_about_all_matieres.clear();
        } catch (DatabaseConnectionException ex) {
            Logger.getLogger(Panel_PresenceUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void checkSeancesAndSaveNewSeance() throws DatabaseConnectionException, SQLException{
        java.util.List<Matiere> list_matiere=matiere_service.getListMatierByDay();// get all Matiere for today 
        List list_previeux=null;
        // for test si seance exit update true= en cours sinon creation Number total of seance in month  
        Seance scence_obj=null;
        for (Matiere matiere : list_matiere) {
            // get seance of matiere today 
            scence_obj=seance_service.GetSeanceByTody(matiere);
            if(scence_obj!=null){
                // 
                list_seance_about_all_matieres.add(scence_obj);
            }else{
                
                list_previeux=seance_service.getListAllSeancePrevieuMonth(matiere); // list [sceance(1....30) ]
                seance_service.saveAllNextSeances(list_previeux);// save next seances about Matiere
                list_seance_about_all_matieres.add(seance_service.GetSeanceByTody(matiere));
            }
        }
        
        
    }
    
    
    public void setSeanceInTable(){
        DefaultTableModel df=(DefaultTableModel)table_seance_to_day.getModel();
        df.setRowCount(0);
        
        for (Seance seance_obj : list_seance_about_all_matieres) {
            Object[]args={seance_obj.getNumSeance(),seance_obj.getMatiere().getMatiereEtdAr(),seance_obj.getMatiere().getNiveau().getNiveauInitialAr(),
                            seance_obj.getMatiere().getCategoreNiveau().getCategore_niveau_ar(),seance_obj.getMatiere().getId(),seance_obj.getId()};
            df.addRow(args);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_presence = new javax.swing.JPanel();
        txt_cod_barr_presence = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        txt_matricul_presence = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        tableScrollButton11 = new ui.table.TableScrollButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        table_seance_to_day = new javax.swing.JTable();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        lab_category_presence = new javax.swing.JLabel();
        lab_niveau_presence = new javax.swing.JLabel();
        lab_nam_presence = new javax.swing.JLabel();
        lab_prenom_presence = new javax.swing.JLabel();
        lab_imag_etud_presence = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        lab_matiere_presence = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        lab_num_seance_presence = new javax.swing.JLabel();
        lab_icon_chech_cross = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        tableScrollButton12 = new ui.table.TableScrollButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        tab_presence = new javax.swing.JTable();
        searchText6 = new material.design.SearchText();
        buttonRounder33 = new material.design.buttonRounder();

        pan_presence.setBackground(new java.awt.Color(255, 255, 255));
        pan_presence.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cod_barr_presence.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_cod_barr_presence.setForeground(new java.awt.Color(102, 102, 102));
        txt_cod_barr_presence.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cod_barr_presence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_cod_barr_presence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_barr_presenceActionPerformed(evt);
            }
        });
        pan_presence.add(txt_cod_barr_presence, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 25, 290, 31));

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pan_presence.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 125, -1));

        txt_matricul_presence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pan_presence.add(txt_matricul_presence, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 25, 191, 31));

        jButton7.setText("payement par moin");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        pan_presence.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 30));

        table_seance_to_day.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم الحصة", "المادة ", "القسم", "المستوى", "N", "id_saence_Matier"
            }
        ));
        jScrollPane11.setViewportView(table_seance_to_day);

        tableScrollButton11.add(jScrollPane11, java.awt.BorderLayout.CENTER);

        pan_presence.add(tableScrollButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 45, 320, 290));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 102, 102));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel47.setText("اللقب");
        pan_presence.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(913, 93, -1, -1));

        jLabel49.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(102, 102, 102));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel49.setText("الاسم");
        pan_presence.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(1115, 85, -1, 25));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(102, 102, 102));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel50.setText("المستوى ");
        pan_presence.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(1096, 122, -1, -1));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(102, 102, 102));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel51.setText("القسم ");
        pan_presence.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(913, 129, -1, -1));

        lab_category_presence.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab_category_presence.setForeground(new java.awt.Color(0, 0, 204));
        lab_category_presence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_category_presence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pan_presence.add(lab_category_presence, new org.netbeans.lib.awtextra.AbsoluteConstraints(954, 122, 136, 24));

        lab_niveau_presence.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab_niveau_presence.setForeground(new java.awt.Color(0, 0, 204));
        lab_niveau_presence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_niveau_presence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pan_presence.add(lab_niveau_presence, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 122, 136, 24));

        lab_nam_presence.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab_nam_presence.setForeground(new java.awt.Color(0, 0, 204));
        lab_nam_presence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_nam_presence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pan_presence.add(lab_nam_presence, new org.netbeans.lib.awtextra.AbsoluteConstraints(954, 85, 136, 25));

        lab_prenom_presence.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab_prenom_presence.setForeground(new java.awt.Color(0, 0, 204));
        lab_prenom_presence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_prenom_presence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pan_presence.add(lab_prenom_presence, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 84, 136, 26));

        lab_imag_etud_presence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_imag_etud_presence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pan_presence.add(lab_imag_etud_presence, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 84, 109, 104));

        jLabel57.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(102, 102, 102));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel57.setText("المادة");
        pan_presence.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 160, 40, -1));

        lab_matiere_presence.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab_matiere_presence.setForeground(new java.awt.Color(0, 0, 204));
        lab_matiere_presence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_matiere_presence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pan_presence.add(lab_matiere_presence, new org.netbeans.lib.awtextra.AbsoluteConstraints(954, 158, 136, 24));

        jLabel59.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(102, 102, 102));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel59.setText("رقم الحصة");
        pan_presence.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 158, -1, 24));

        lab_num_seance_presence.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab_num_seance_presence.setForeground(new java.awt.Color(204, 0, 0));
        lab_num_seance_presence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_num_seance_presence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pan_presence.add(lab_num_seance_presence, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 158, 70, 24));
        pan_presence.add(lab_icon_chech_cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 194, 72, 64));

        jButton8.setText("payemenrt par seance ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        pan_presence.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, -1));

        tab_presence.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "المادة", "القسم", "المستوى", "الاسم و اللقب", "Id_etud", "Id_seance", "Title 7"
            }
        ));
        jScrollPane12.setViewportView(tab_presence);

        tableScrollButton12.add(jScrollPane12, java.awt.BorderLayout.CENTER);

        pan_presence.add(tableScrollButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 287, 610, 250));

        searchText6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        searchText6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pan_presence.add(searchText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 258, 27));

        buttonRounder33.setBackground(new java.awt.Color(153, 0, 153));
        buttonRounder33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRounder33ActionPerformed(evt);
            }
        });
        pan_presence.add(buttonRounder33, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pan_presence, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pan_presence, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cod_barr_presenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_barr_presenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_barr_presenceActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //matier of to day
        
        //  Payement payement = payementDAOImpl.findById(1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void buttonRounder33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRounder33ActionPerformed
        
    }//GEN-LAST:event_buttonRounder33ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.buttonRounder buttonRounder33;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JLabel lab_category_presence;
    private javax.swing.JLabel lab_icon_chech_cross;
    private javax.swing.JLabel lab_imag_etud_presence;
    private javax.swing.JLabel lab_matiere_presence;
    private javax.swing.JLabel lab_nam_presence;
    private javax.swing.JLabel lab_niveau_presence;
    private javax.swing.JLabel lab_num_seance_presence;
    private javax.swing.JLabel lab_prenom_presence;
    private javax.swing.JPanel pan_presence;
    private material.design.SearchText searchText6;
    private javax.swing.JTable tab_presence;
    private ui.table.TableScrollButton tableScrollButton11;
    private ui.table.TableScrollButton tableScrollButton12;
    private javax.swing.JTable table_seance_to_day;
    private javax.swing.JTextField txt_cod_barr_presence;
    private javax.swing.JTextField txt_matricul_presence;
    // End of variables declaration//GEN-END:variables
}
